#!/usr/bin/env bash
# Self-install: copy this unpacked pack into the shared RetComM toolchain cache
# and add it to the user shell PATH (idempotent).
#
# Run from the extracted zip root:
#   ./install.sh
#   ./install.sh --force
set -euo pipefail

PACK_ID="${RETCOMM_PACK_ID:-cmake-clang-v1}"
MARKER_BEGIN="# >>> retcomm-toolchain (${PACK_ID}) >>>"
MARKER_END="# <<< retcomm-toolchain (${PACK_ID}) <<<"
FORCE=0

usage() {
  cat <<EOF
Usage: ./install.sh [--force] [--help]

Install this toolchain pack into the shared RetComM cache and add
\`…/toolchains/${PACK_ID}/latest/bin\` to your login PATH (idempotent).

Options:
  --force   Replace an existing matching <tag>/ directory
  --help    Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    --force) FORCE=1; shift ;;
    *) echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

PACK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CMAKE_BIN="${PACK_ROOT}/bin/cmake"
[[ -x "$CMAKE_BIN" || -f "$CMAKE_BIN" ]] || {
  echo "error: bin/cmake missing — run this from the extracted pack root" >&2
  exit 1
}

retcomm_data_home() {
  if [[ -n "${RETCOMM_DATA_HOME:-}" ]]; then
    printf '%s\n' "${RETCOMM_DATA_HOME}"
  elif [[ -n "${XDG_DATA_HOME:-}" ]]; then
    printf '%s\n' "${XDG_DATA_HOME}/retcomm"
  else
    printf '%s\n' "${HOME}/.local/share/retcomm"
  fi
}

cache_root() {
  if [[ -n "${RETCOMM_TOOLCHAIN_CACHE:-}" ]]; then
    printf '%s\n' "${RETCOMM_TOOLCHAIN_CACHE}"
  else
    printf '%s\n' "$(retcomm_data_home)/toolchains/${PACK_ID}"
  fi
}

read_version() {
  local meta="${PACK_ROOT}/retcomm-toolchain.json"
  [[ -f "$meta" ]] || { echo "offline"; return; }
  if command -v python3 >/dev/null 2>&1; then
    python3 -c 'import json,sys; print(json.load(open(sys.argv[1],encoding="utf-8")).get("version","offline").strip() or "offline")' "$meta" 2>/dev/null && return
  fi
  local v
  v="$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$meta" | head -1)"
  printf '%s\n' "${v:-offline}"
}

sanitize_tag() {
  local s="$1"
  s="${s//[^A-Za-z0-9._-]/_}"
  printf '%s\n' "${s:-offline}"
}

path_has_dir() {
  local needle="$1"
  local IFS=':'
  local p
  for p in ${PATH:-}; do
    [[ "$p" == "$needle" ]] && return 0
  done
  return 1
}

prepend_path_session() {
  local dir="$1"
  if path_has_dir "$dir"; then
    return 0
  fi
  export PATH="${dir}${PATH:+:${PATH}}"
}

# Remove any existing marker block, then append a fresh one.
upsert_profile_block() {
  local file="$1" block="$2"
  local tmp
  tmp="$(mktemp)"
  if [[ -f "$file" ]]; then
    awk -v b="$MARKER_BEGIN" -v e="$MARKER_END" '
      $0 == b { skip=1; next }
      $0 == e { skip=0; next }
      !skip { print }
    ' "$file" >"$tmp"
  else
    : >"$tmp"
  fi
  # Ensure trailing newline before block
  if [[ -s "$tmp" ]] && [[ "$(tail -c1 "$tmp" | wc -l)" -eq 0 ]]; then
    printf '\n' >>"$tmp"
  fi
  printf '%s\n' "$block" >>"$tmp"
  mkdir -p "$(dirname "$file")"
  mv "$tmp" "$file"
}

CACHE="$(cache_root)"
VER="$(read_version)"
TAG="$(sanitize_tag "$VER")"
DEST="${CACHE}/${TAG}"
LATEST="${CACHE}/latest"
BIN_DIR="${LATEST}/bin"
HOOK="${CACHE}/path.sh"

mkdir -p "$CACHE"

if [[ -e "$DEST" && "$FORCE" != "1" ]]; then
  if [[ -f "${DEST}/bin/cmake" || -x "${DEST}/bin/cmake" ]]; then
    echo "Already installed at ${DEST} (pass --force to replace)."
  else
    FORCE=1
  fi
fi

if [[ "$FORCE" == "1" || ! -e "$DEST" ]]; then
  echo "Installing ${PACK_ID} ${VER} → ${DEST}"
  rm -rf "$DEST"
  mkdir -p "$DEST"
  # Copy pack contents; skip VCS noise if any.
  if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete \
      --exclude '.git/' \
      --exclude '.staging-install/' \
      "${PACK_ROOT}/" "${DEST}/"
  else
    # Portable fallback
    tar -C "$PACK_ROOT" -cf - . | tar -C "$DEST" -xf -
  fi
else
  echo "Keeping existing ${DEST}"
fi

# Refresh latest pointer (symlink preferred; copy fallback).
if [[ -e "$LATEST" || -L "$LATEST" ]]; then
  if [[ -L "$LATEST" || -f "$LATEST" ]]; then
    rm -f "$LATEST"
  else
    rm -rf "$LATEST"
  fi
fi
if ln -s "$DEST" "$LATEST" 2>/dev/null; then
  :
else
  cp -a "$DEST" "$LATEST"
fi

# Hook sourced by shell profiles — prefers latest/env.sh when present.
cat >"$HOOK" <<EOF
# Auto-generated by ${PACK_ID} install.sh — do not edit; re-run install to refresh.
RETCOMM_TC_LATEST="${LATEST}"
if [[ -f "\${RETCOMM_TC_LATEST}/env.sh" ]]; then
  # shellcheck disable=SC1091
  . "\${RETCOMM_TC_LATEST}/env.sh"
elif [[ -d "\${RETCOMM_TC_LATEST}/bin" ]]; then
  case ":\${PATH}:" in
    *":\${RETCOMM_TC_LATEST}/bin:"*) ;;
    *) export PATH="\${RETCOMM_TC_LATEST}/bin\${PATH:+:\${PATH}}" ;;
  esac
fi
export RETCOMM_TOOLCHAIN_DIR="\${RETCOMM_TC_LATEST}"
EOF

PROFILE_BLOCK="${MARKER_BEGIN}
# Managed by ${PACK_ID} install/uninstall — safe to delete via uninstall.sh
if [ -f \"${HOOK}\" ]; then
  # shellcheck disable=SC1091
  . \"${HOOK}\"
fi
${MARKER_END}"

# Touch common interactive shells; create .profile block at least.
PROFILES=()
[[ -f "${HOME}/.bashrc" ]] && PROFILES+=("${HOME}/.bashrc")
[[ -f "${HOME}/.zshrc" ]] && PROFILES+=("${HOME}/.zshrc")
[[ -f "${HOME}/.profile" ]] && PROFILES+=("${HOME}/.profile")
if [[ ${#PROFILES[@]} -eq 0 ]]; then
  # Prefer bashrc on Linux, zshrc on macOS when neither exists yet.
  if [[ "$(uname -s 2>/dev/null || true)" == Darwin ]]; then
    PROFILES+=("${HOME}/.zshrc")
  else
    PROFILES+=("${HOME}/.bashrc")
  fi
fi

for rc in "${PROFILES[@]}"; do
  upsert_profile_block "$rc" "$PROFILE_BLOCK"
  echo "Updated PATH hook in ${rc}"
done

# Also ensure .profile gets the block when we only touched bashrc/zshrc,
# so login shells pick it up — but only if .profile already exists or we
# created one of the interactive files above without .profile.
if [[ ! -f "${HOME}/.profile" ]]; then
  # Don't create .profile unless nothing else was available earlier — already handled.
  :
fi

prepend_path_session "$BIN_DIR"
export RETCOMM_TOOLCHAIN_DIR="$LATEST"

# Idempotent: if bin was already on PATH earlier in the list, leave it;
# we only prepend when missing. env.sh may also prepend in new shells via hook.

cat <<EOF

Installed ${PACK_ID} ${VER}
  Pack:  ${DEST}
  PATH:  ${BIN_DIR}  (via shell profile + this session)

Open a new terminal, or run:
  . "${HOOK}"

Verify:
  command -v cmake && cmake --version

Uninstall later (from this zip or from the cache copy):
  ./uninstall.sh
EOF
